name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: xcodebuild clean build test -project Artworks.xcodeproj -scheme Artworks -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -enableCodeCoverage YES -derivedDataPath Build/ CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Convert test coverage to SonarQube format
        run: bash ./.github/scripts/xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ >Coverage.xml
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: Coverage.xml
          retention-days: 5
  sonarcloud:
    name: SonarCloud
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download test coverage
        uses: actions/download-artifact@v3
        with:
          name: test-coverage
      - name: Fix paths in coverage report
        run: sed -i 's#/Users/runner/work/artworks/artworks#/github/workspace#g' Coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverageReportPaths=Coverage.xml
